// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type Editor struct {
	ID         int64
	QuestionID string
	Lang       string
	LangSlug   string
	Code       string
}

type Hint struct {
	ID         int64
	QuestionID string
	Hint       string
}

type Question struct {
	ID         int64
	QuestionID string
	Link       string
	Title      string
	TitleSlug  string
	IsPaidOnly bool
	Difficulty string
	Content    string
}
